#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 14 08:35:50 2018

@author: oster
"""

#epsilon - greedy - methods
def eps_greed(value_function, current_state, player, moves, isFeasableStep, eps):
    v=0
    action=[]
    if(player==1):
        for m in moves:
            if (isFeasableStep(m)):
                if v<= value_function(m):
                    v=value_function(m)
                    action.append(m)
        if 
            